"use strict";

// DEPENDENCIES
// ------------
// External
import path from "path";
import url from "url";
// Local


// CONSTANTS
// ---------

const FILENAME = url.fileURLToPath(import.meta.url);
const SHELF_ROOT_DIRECTORY_PATH = path.join(path.dirname(FILENAME), "../..");

const BACKEND_DIRECTORY_PATH = path.join(SHELF_ROOT_DIRECTORY_PATH, "backend");
    const BACKEND_RECORDS_DIRECTORY_PATH = path.join(BACKEND_DIRECTORY_PATH, "records");
    const BACKEND_BOOKS_DIRECTORY_PATH = path.join(BACKEND_DIRECTORY_PATH, "books");
    const BACKEND_BOARD_GAMES_DIRECTORY_PATH = path.join(BACKEND_DIRECTORY_PATH, "boardGames");
    const BACKEND_COMMON_DIRECTORY_PATH = path.join(BACKEND_DIRECTORY_PATH, "common");
    const BACKEND_DB_DIRECTORY_PATH = path.join(BACKEND_DIRECTORY_PATH, "db");
    const BACKEND_RESOURCES_DIRECTORY_PATH = path.join(BACKEND_DIRECTORY_PATH, "resources");

const FRONTEND_DIRECTORY_PATH = path.join(SHELF_ROOT_DIRECTORY_PATH, "frontend");
    const FRONTEND_STATIC_DIRECTORY_PATH = path.join(FRONTEND_DIRECTORY_PATH, "static");
        const FRONTEND_IMAGES_DIRECTORY_PATH = path.join(FRONTEND_STATIC_DIRECTORY_PATH, "images");
            const FRONTEND_RECORD_CACHE_DIRECTORY_PATH = path.join(FRONTEND_IMAGES_DIRECTORY_PATH, "records");
            const FRONTEND_BOARD_GAME_CACHE_DIRECTORY_PATH = path.join(FRONTEND_IMAGES_DIRECTORY_PATH, "board-games");
            const FRONTEND_BOOK_CACHE_DIRECTORY_PATH = path.join(FRONTEND_IMAGES_DIRECTORY_PATH, "books");
    const FRONTEND_LIQUID_DIRECTORY_PATH = path.join(FRONTEND_DIRECTORY_PATH, "liquid");
        const FRONTEND_INCLUDES_DIRECTORY_PATH = path.join(FRONTEND_LIQUID_DIRECTORY_PATH, "_includes");
        const FRONTEND_LAYOUTS_DIRECTORY_PATH = path.join(FRONTEND_LIQUID_DIRECTORY_PATH, "_layouts");

export default {
    SHELF_ROOT_DIRECTORY_PATH,
    BACKEND_DIRECTORY_PATH,
    BACKEND_RECORDS_DIRECTORY_PATH,
    BACKEND_BOOKS_DIRECTORY_PATH,
    BACKEND_BOARD_GAMES_DIRECTORY_PATH,
    BACKEND_COMMON_DIRECTORY_PATH,
    BACKEND_DB_DIRECTORY_PATH,
    BACKEND_RESOURCES_DIRECTORY_PATH,
    FRONTEND_DIRECTORY_PATH,
    FRONTEND_STATIC_DIRECTORY_PATH,
    FRONTEND_IMAGES_DIRECTORY_PATH,
    FRONTEND_RECORD_CACHE_DIRECTORY_PATH,
    FRONTEND_BOARD_GAME_CACHE_DIRECTORY_PATH,
    FRONTEND_BOOK_CACHE_DIRECTORY_PATH,
    FRONTEND_LIQUID_DIRECTORY_PATH,
    FRONTEND_INCLUDES_DIRECTORY_PATH,
    FRONTEND_LAYOUTS_DIRECTORY_PATH
}
