"use strict";

const RECORD_COLLECTION = "recordCollection";
const RECORD_WISHLIST = "recordWishlist";
const INITIAL_RECORD_COLLECTION_IN_PROGRESS = "initialRecordCollectionInProgress";
const REMOVED_RECORD_FROM_COLLECTION = "removeRecordFromCollection";
const REMOVED_RECORD_FROM_WISHLIST = "removeRecordFromWishlist";
const ADDED_RECORD_TO_COLLECTION = "addRecordToCollection";
const ADDED_RECORD_TO_WISHLIST = "addRecordToWishlist";
const UPDATED_RECORD_IN_COLLECTION = "updateRecordInCollection";
const UPDATED_RECORD_IN_WISHLIST = "updateRecordInWishlist";

const BOARD_GAME_COLLECTION = "boardGameCollection";
const BOARD_GAME_WISHLIST = "boardGameWishlist";
const INITIAL_BOARD_GAME_COLLECTION_IN_PROGRESS = "initialBoardGameCollectionInProgress";
const REMOVED_BOARD_GAME_FROM_COLLECTION = "removeBoardGameFromCollection";
const REMOVED_BOARD_GAME_FROM_WISHLIST = "removeBoardGameFromWishlist";
const ADDED_BOARD_GAME_TO_COLLECTION = "addBoardGameToCollection";
const ADDED_BOARD_GAME_TO_WISHLIST = "addBoardGameToWishlist";
const UPDATED_BOARD_GAME_IN_COLLECTION = "updateBoardGameInCollection";
const UPDATED_BOARD_GAME_IN_WISHLIST = "updateBoardGameInWishlist";

const GOODREADS_OAUTH_GRANTED = "goodreadsOauthGranted";
const BOOK_COLLECTION = "bookCollection";
const BOOK_WISHLIST = "bookWishlist";
const INITIAL_BOOK_COLLECTION_IN_PROGRESS = "initialBookCollectionInProgress";
const REMOVED_BOOK_FROM_COLLECTION = "removeBookFromCollection";
const REMOVED_BOOK_FROM_WISHLIST = "removeBookFromWishlist";
const ADDED_BOOK_TO_COLLECTION = "addBookToCollection";
const ADDED_BOOK_TO_WISHLIST = "addBookToWishlist";
const UPDATED_BOOK_IN_COLLECTION = "updateBookInCollection";
const UPDATED_BOOK_IN_WISHLIST = "updateBookInWishlist";

const CLEAR_CACHE = "clearCache";

export default {
    RECORD_COLLECTION,
    RECORD_WISHLIST,
    INITIAL_RECORD_COLLECTION_IN_PROGRESS,
    REMOVED_RECORD_FROM_COLLECTION,
    REMOVED_RECORD_FROM_WISHLIST,
    ADDED_RECORD_TO_COLLECTION,
    ADDED_RECORD_TO_WISHLIST,
    UPDATED_RECORD_IN_COLLECTION,
    UPDATED_RECORD_IN_WISHLIST,
    BOARD_GAME_COLLECTION,
    BOARD_GAME_WISHLIST,
    INITIAL_BOARD_GAME_COLLECTION_IN_PROGRESS,
    REMOVED_BOARD_GAME_FROM_COLLECTION,
    REMOVED_BOARD_GAME_FROM_WISHLIST,
    ADDED_BOARD_GAME_TO_COLLECTION,
    ADDED_BOARD_GAME_TO_WISHLIST,
    UPDATED_BOARD_GAME_IN_COLLECTION,
    UPDATED_BOARD_GAME_IN_WISHLIST,
    GOODREADS_OAUTH_GRANTED,
    BOOK_COLLECTION,
    BOOK_WISHLIST,
    INITIAL_BOOK_COLLECTION_IN_PROGRESS,
    REMOVED_BOOK_FROM_COLLECTION,
    REMOVED_BOOK_FROM_WISHLIST,
    ADDED_BOOK_TO_COLLECTION,
    ADDED_BOOK_TO_WISHLIST,
    UPDATED_BOOK_IN_COLLECTION,
    UPDATED_BOOK_IN_WISHLIST,
    CLEAR_CACHE
}
